name: Spring EC2 자동 배포

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 레포지토리 가져오기
        uses: actions/checkout@v4

      - name: JDK 17 설치
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: gradlew 권한 부여
        run: chmod +x gradlew

      - name: 프로젝트 빌드
        run: ./gradlew clean bootJar -x test --no-daemon

      - name: EC2 기존 jar 정리
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            mkdir -p /home/ubuntu/OngoJishik-BE/build/libs
            rm -f /home/ubuntu/OngoJishik-BE/build/libs/*.jar

      - name: jar 파일 EC2 업로드
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "build/libs/*.jar"
          target: "/home/ubuntu/OngoJishik-BE"

      - name: EC2 애플리케이션 재시작
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          command_timeout: 5m
          script: |
            set -e

            sudo systemctl restart ongojisik
            sudo systemctl status ongojisik --no-pager
